import datetime
import google.generativeai as genai
from django.conf import settings
from django.db.models import Sum
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from portfolio.models import Portfolio
from portfolio.utils import get_stock_price
from transactions.models import Transaction
from analytics.models import Budget

@api_view(['POST'])
@permission_classes([IsAuthenticated])
def chat_with_gemini(request):
    """
    Personal Gemini Financial Assistant Chat Endpoint.
    Accepts:
    - message (str): The current user message.
    - history (list): List of chat history objects like {"role": "user"|"assistant", "content": "..."}.
    Returns:
    - response (str): The text response generated by Gemini.
    """
    user_message = request.data.get('message')
    history_data = request.data.get('history', [])

    if not user_message:
        return Response({"error": "Message is required."}, status=400)

    # 1. Check if Gemini API key is configured
    api_key = getattr(settings, 'GEMINI_API_KEY', '')
    if not api_key:
        return Response({
            "error": "Gemini API Key is not configured. Please set GEMINI_API_KEY in your .env file."
        }, status=500)

    # 2. Gather User Context: Portfolio, Budgets, Transactions
    user = request.user
    today = datetime.date.today()
    current_time_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # A. Portfolio holdings context
    stocks = Portfolio.objects.filter(user=user)
    portfolio_details = []
    total_investment = 0.0
    total_current_value = 0.0

    for stock in stocks:
        current_price = get_stock_price(stock.stock_name)
        investment = stock.quantity * float(stock.buy_price)
        current_value = stock.quantity * current_price
        profit_loss = current_value - investment
        roi = (profit_loss / investment * 100) if investment > 0 else 0.0
        
        portfolio_details.append(
            f"- {stock.stock_name}: {stock.quantity} shares, "
            f"Avg Buy Price: Rs {stock.buy_price:.2f}, "
            f"Current Price: Rs {current_price:.2f}, "
            f"Total Investment: Rs {investment:.2f}, "
            f"Current Value: Rs {current_value:.2f}, "
            f"Profit/Loss: Rs {profit_loss:.2f} ({roi:.2f}%)"
        )
        total_investment += investment
        total_current_value += current_value

    overall_profit = total_current_value - total_investment
    overall_roi = (overall_profit / total_investment * 100) if total_investment > 0 else 0.0

    portfolio_context = (
        f"Total Investment Cost: Rs {total_investment:.2f}\n"
        f"Total Current Value: Rs {total_current_value:.2f}\n"
        f"Overall Net Profit/Loss: Rs {overall_profit:.2f} ({overall_roi:.2f}%)\n"
        "Holdings Breakdown:\n" + ("\n".join(portfolio_details) if portfolio_details else "No current stock holdings.")
    )

    # B. Current Month Budgets context
    month_date = today.replace(day=1)
    budgets = Budget.objects.filter(user=user, month=month_date)
    budget_details = []
    
    for b in budgets:
        actual_spent = Transaction.objects.filter(
            user=user,
            category=b.category,
            type='expense',
            date__year=month_date.year,
            date__month=month_date.month
        ).aggregate(total=Sum('amount'))['total'] or 0.0

        remaining = float(b.amount) - float(actual_spent)
        percent_spent = (float(actual_spent) / float(b.amount) * 100) if b.amount > 0 else 0.0
        
        budget_details.append(
            f"- {b.category.name}: Limit Rs {b.amount:.2f}, "
            f"Spent: Rs {actual_spent:.2f}, "
            f"Remaining: Rs {remaining:.2f} ({percent_spent:.1f}% spent)"
        )
    
    budget_context = (
        f"Month: {today.strftime('%B %Y')}\n" +
        ("\n".join(budget_details) if budget_details else "No budgets configured for this month.")
    )

    # C. Recent Transactions (last 30 items)
    recent_txs = Transaction.objects.filter(user=user).order_by('-date', '-id')[:30]
    txs_details = []
    for tx in recent_txs:
        desc = f" ({tx.description})" if tx.description else ""
        txs_details.append(
            f"- {tx.date.strftime('%Y-%m-%d')} | {tx.type.upper()} | "
            f"Rs {tx.amount:.2f} | Category: {tx.category.name if tx.category else 'Uncategorized'}{desc}"
        )
    
    transactions_context = (
        "Recent 30 Transactions:\n" + ("\n".join(txs_details) if txs_details else "No transactions recorded yet.")
    )

    # D. Full context assembly
    context_str = f"""
[AUTHENTICATED USER DETAILS]
Username: {user.username}
Email: {user.email}
Current Time: {current_time_str}

[PORTFOLIO SUMMARY]
{portfolio_context}

[BUDGET STATUS (CURRENT MONTH)]
{budget_context}

[TRANSACTION JOURNAL]
{transactions_context}
"""

    # 3. Configure Gemini Generative AI
    try:
        genai.configure(api_key=api_key)
        
        system_instruction = (
            "You are Antigravity, a professional, secure, and smart personal finance AI assistant. "
            "You help users manage their money, budgets, stock transactions, and investments. "
            "You are provided with real-time financial context of the authenticated user. "
            "Analyze the user's data and answer their queries concisely, helpfully, and accurately. "
            "Refer to currency in Rupees (Rs) and not dollars. "
            "Be positive, clear, and action-oriented. "
            "Do not make up information that is not present in the context. "
            "If the user asks questions unrelated to finance or their account, politely guide them back to their personal finances."
        )

        model = genai.GenerativeModel(
            model_name='gemini-2.5-flash',
            system_instruction=system_instruction
        )

        # Format history data for Gemini chat session
        gemini_history = []
        for msg in history_data:
            role = 'user' if msg.get('role') == 'user' else 'model'
            gemini_history.append({
                'role': role,
                'parts': [msg.get('content', '')]
            })

        # Start chat session
        chat = model.start_chat(history=gemini_history)
        
        # Inject the live context alongside the current message
        prompt_with_context = f"[Live Database Context]\n{context_str}\n\n[User Request]\n{user_message}"
        
        response = chat.send_message(prompt_with_context)
        return Response({"response": response.text}, status=200)

    except Exception as e:
        return Response({
            "error": f"An error occurred while calling the Gemini API: {str(e)}"
        }, status=500)
