version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: fintech_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: fintech_app
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/fintech_db"
      SECRET_KEY: "django-insecure-d=bimep!q11hse5=d=et-82m4zm^_86!1jf7kvyd9gm@5kv_s)"
      DEBUG: "True"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: